"use client";

import * as Dialog from "@radix-ui/react-dialog";
import { Plus, Trash2, X } from "lucide-react";
import { useState, type FormEvent } from "react";

export interface TaskLabelOption { id: string; name: string; color: string }

export function TaskLabelSettingsDialog({ open, spaceId, labels, onOpenChange }: { open: boolean; spaceId: string; labels: readonly TaskLabelOption[]; onOpenChange(open: boolean): void }) {
  const [items, setItems] = useState(labels); const [name, setName] = useState(""); const [color, setColor] = useState("#0969da"); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null);
  async function submit(event: FormEvent) { event.preventDefault(); if (!name.trim()) { setError("请输入标签名称"); return; } setPending(true); setError(null); const id = `label:${spaceId}:${Date.now()}`; const response = await fetch("/api/task-labels", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ id, spaceId, name, color }) }); const body = await response.json() as { ok: boolean; label?: TaskLabelOption; error?: string }; if (response.ok && body.ok && body.label) { setItems((current) => [...current, body.label!]); setName(""); } else setError(body.error ?? "标签创建失败"); setPending(false); }
  async function remove(item: TaskLabelOption) { setPending(true); setError(null); const response = await fetch("/api/task-labels", { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ spaceId, labelId: item.id }) }); const body = await response.json() as { ok: boolean; code?: string; error?: string }; if (response.ok && body.ok) setItems((current) => current.filter((candidate) => candidate.id !== item.id)); else setError(body.code === "version_conflict" ? "请先从任务中移除该标签，再删除标签。" : body.error ?? "标签删除失败"); setPending(false); }
  return <Dialog.Root open={open} onOpenChange={(next) => !pending && onOpenChange(next)}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-[60] bg-[#1f2328]/45" /><Dialog.Content className="fixed inset-x-0 bottom-0 z-[60] max-h-[90vh] overflow-y-auto border border-[#d0d7de] bg-white outline-none sm:left-1/2 sm:top-1/2 sm:bottom-auto sm:w-[min(92vw,520px)] sm:-translate-x-1/2 sm:-translate-y-1/2 sm:rounded-lg"><div className="flex items-start border-b border-[#d0d7de] px-5 py-4"><div className="min-w-0 flex-1"><Dialog.Title className="font-semibold">标签设置</Dialog.Title><Dialog.Description className="mt-1 text-sm text-[#57606a]">标签属于当前工作空间。</Dialog.Description></div><button aria-label="关闭标签设置" onClick={() => onOpenChange(false)} className="grid h-8 w-8 place-items-center"><X size={17} /></button></div><div className="grid gap-4 p-5">{error ? <div role="alert" className="rounded-md border border-[#f1aeb5] bg-[#fff5f5] px-3 py-2 text-sm text-[#cf222e]">{error}</div> : null}<div className="flex flex-wrap gap-2">{items.map((item) => <span key={item.id} className="inline-flex items-center gap-1 rounded-md border px-2 py-1 text-sm" style={{ borderColor: item.color, color: item.color }}>{item.name}<button aria-label={`删除${item.name}`} onClick={() => void remove(item)} className="grid h-6 w-6 place-items-center"><Trash2 size={13} /></button></span>)}</div><form onSubmit={(event) => void submit(event)} className="grid gap-3 border-t border-[#d8dee4] pt-4 sm:grid-cols-[1fr_90px_auto]"><input aria-label="标签名称" value={name} onChange={(e) => setName(e.target.value)} className="h-10 rounded-md border border-[#8c959f] px-3 text-sm" /><input aria-label="标签颜色" type="color" value={color} onChange={(e) => setColor(e.target.value)} className="h-10 w-full rounded-md border border-[#8c959f] p-1" /><button disabled={pending} aria-label="创建标签" className="inline-flex h-10 items-center gap-1 rounded-md bg-[#1f883d] px-3 text-sm font-semibold text-white"><Plus size={15} />创建标签</button></form></div></Dialog.Content></Dialog.Portal></Dialog.Root>;
}
